import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={"bg-gradient-to-r from-indigo-500 via-purple-500 via-30% to-pink-500"}>
        <h1 className={""}>page</h1>
        {children}
        </body>
        </html>
    )
}
